# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='contentType',
            new_name='content_type',
        ),
    ]
